### ISSUE TITLE
Cannot delete repos owned by other users

### ISSUE THREAD

**Issue by ConstipatedNinja** [felixrieseberg/windows95#1]
You win. I think it's time now for humanity to just call it a day and stop existing.

**Comment by RedShift1** [comment]
Make Windows 95 great again!

**Comment by pinobatch** [comment]
Is this supposed to allude to @Microsoft being the rightful owner of part of this repo?

**Comment by jacktuck** [comment]
```sudo rm -rf felixrieseberg/windows95```
