### ISSUE TITLE
DirectSound

### ISSUE THREAD

**Issue by Tamamo-no-Bae** [felixrieseberg/windows95#107]
Currently I am trying to get one of my all-time favorite games working that is completely broken on modern OS. Evolution - The game of Intelligent Life

I've reached the point where the game boots but shuts down because it cannot initiate DirectSound, I've been unable to find any fix for this. Is there a way to emulate DirectSound?

**Comment by felixrieseberg** [comment]
Sound is now fixed, thanks for reporting!
