### ISSUE TITLE
Fun idea: Windows 3.1 version

### ISSUE THREAD

**Issue by rjzak** [felixrieseberg/windows95#108]
Windows 95 was fun, but how about back a little further and do the same thing for Windows 3.1?

**Comment by CreeperDude372** [comment]
Um... is this an issue? But that is pretty cool. HOW ABOUT WINDOSW 10?!

**Comment by kaylinDevelopment** [comment]
Yes, @rjzak. I definitely will fork and see what I can do. Thanks for the idea! ❤️

**Comment by felixrieseberg** [comment]
Seems like y'all have it under control. Good luck!
