### ISSUE TITLE
But will it run doom?

### ISSUE THREAD

**Issue by Bored0ne** [felixrieseberg/windows95#11]
Legit question, I don't wanna have to run a true vm to play old school games.

**Comment by felixrieseberg** [comment]
Probably! Chances are _very_ high that you actually want to use a real VM software though  😉 

Otherwise, try to add a `cdrom` image here: https://github.com/felixrieseberg/windows95/blob/master/src/renderer/renderer.js#L17-L25

I might also add the ability to easily drag and drop files.

**Comment by uotw** [comment]
I installed doom2 on the Window image file (free [here](https://www.doomworld.com/idgames/idstuff/doom/win95/doom95)). Had to un-asar source into /Contents/Resources/app first, then mounted
/Contents/Resources/app/src/renderer/images/windows95.img
and added my file.
Launches but unplayable on my 1 year old MBP.

**Comment by uotw** [comment]
![2018-8-23_15 13 54_sono](https://user-images.githubusercontent.com/14109479/44546839-2e586000-a6e7-11e8-9c23-0ac9febccb35.gif)

**Comment by alexpersian** [comment]
@uotw where did you add the DOOM file/directory?

Tried the following without success:
- unpack app.asar into /app
- mount windows95 image
- add DOOM directory w/WAD file into the Program Files directory
- pack /app into app.asar
- relaunch and reset state

**Comment by alexpersian** [comment]
Removing the default state file worked, thanks!

**Comment by alexpersian** [comment]
I just wish this issue had been titled: "Will it run DOOM?"

**Comment by smaslennikov** [comment]
@alexpersian there's always time to rename. cough cough.

**Comment by Bored0ne** [comment]
Fixed it, I’m glad you guys new what I meant

**Comment by uotw** [comment]
If anyone wants a command line method to set up doom using this app on MacOS here ya go.  Depends on node to un-asar.
```
cd ~/Desktop
mkdir win95doom && cd win95doom/
wget "https://github.com/felixrieseberg/windows95/releases/download/v1.0.0/windows95-1.0.0-macos.zip"
unzip windows95-1.0.0-macos.zip && rm windows95-1.0.0-macos.zip 
cd windows95.app/Contents/Resources/
mkdir app
npm install -g asar
asar extract app.asar app/ && rm app.asar 
cd app/src/renderer/images/
rm default-state.bin 
hdiutil attach windows95.img 
wget "http://youfailit.net/pub/idgames/idstuff/doom/win95/doom95.zip"
unzip doom95.zip -d /Volumes/Untitled/Program\ Files/doom/ && rm doom95.zip
```

**Comment by DisplacedGamers** [comment]
Hey guys - I dropped the desktop to 640x480 @ 256 colors, and that got it going. I had to do that for quite a few games back when I was running Sierra games (among others) 20 years ago in Windows 98.

I did have trouble with anything requiring a reboot, but the apply settings without restarting worked for me. Give it a go! I am sure some of you have nicer systems than I do. (Core i7 2600K)

I made a video to show the gameplay speed and framerate. It did run at 640x480 as well, but it was quite sluggish.

https://youtu.be/xDXqmdFxofM

**Comment by felixrieseberg** [comment]
@DisplacedGamers Thank you! 

If someone wants to PR anything here, I'd love to take it!

**Comment by Cak3IsALi3** [comment]
I was wondering if anyone got this working on the windows version of the windows95 and if so how they did it, because I couldn't figure out how to add files to the program.

**Comment by felixrieseberg** [comment]
Doom is now included 🎉

**Comment by uotw** [comment]
> Doom is now included 🎉

Runs well here at ~320x240 but no sound.  Running the doom setup exe files results in a video corrupted window that requires me to delete the state and restart Windoze.
