### ISSUE TITLE
i can't open img file 

### ISSUE THREAD

**Issue by Gruby5588** [felixrieseberg/windows95#113]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

**Comment by parkerlreed** [comment]
You didn't actually describe anything.... you have to actually fill out the template.
