### ISSUE TITLE
Releases Link Wrong

### ISSUE THREAD

**Issue by TehPsychedelic** [felixrieseberg/windows95#119]
Hello,

Can't send a PR for such simple thing because this is an issue with latest release _text_
https://github.com/felixrieseberg/windows95/releases/tag/v2.0.0

Link for standalone x64 windows is wrong, currently:
`https://github.com/felixrieseberg/windows95/releases/download/v2.0.0/windows95-win32-2.0.0-standalone-x64.zip`
Should be
`https://github.com/felixrieseberg/windows95/releases/download/v2.0.0/windows95-2.0.0-win32-standalone-x64.zip`

README is ok.

**Comment by felixrieseberg** [comment]
Dang, thank you for calling that out. Now fixed!
