### ISSUE TITLE
Where is the windows95.img file?

### ISSUE THREAD

**Issue by MeviTheLoser** [felixrieseberg/windows95#121]
I keep coming to the conclusion that in order to actually put my own files on this i need to find and open a windows95.img file (I don't actually know what i'm doing but i read #93 and thats what i came to) but i am either really dumb or just bad at computers and have no idea where to find a windows95.img file and am very confused. please help. i'm on windows 10

**Comment by zlours** [comment]
C:\Users\Support\Downloads\windows95-win32-x64\resources\app.asar.unpacked\src\images\windows95.img

**Comment by MeviTheLoser** [comment]
Thank you!
