### ISSUE TITLE
Running Windows 95 on iPhone

### ISSUE THREAD

**Issue by jsfan3** [felixrieseberg/windows95#125]
I've just discovered this project.
Is it possible to run Windows 95 on an iPhone?

**Comment by AbsurdMagpieScrutinies** [comment]
Now that's truely warped.

**Comment by kaylinDevelopment** [comment]
Well. @copy's [v86](http://www.github.com/copy/v86) (which this project is based off) can emulate many operating systems (including Windows 95) through pure JavaScript. We can fork v86 and create a web application to run on the iPhone.

**Comment by felixrieseberg** [comment]
This project will only run on desktop operating systems, I'm afraid.
