### ISSUE TITLE
Make a Desktop, Console or Web Application for Win95

### ISSUE THREAD

**Issue by gokayokutucu** [felixrieseberg/windows95#134]
Hi all,
Simply I want to make an app which is based CRUD operations. I'm just wondering that can we develop an app for Win95? Is there any instruction for that? 

Thanks,

**Comment by felixrieseberg** [comment]
I'm not quite sure I understand - do you want to build something _inside_ of Windows 95?

**Comment by gokayokutucu** [comment]
Yes, I was asking to build something inside of Win95. I have goodled it but I couldn't find any result. 

Anyway, I solved this issue two weeks ago. Thanks : )
