### ISSUE TITLE
Javascript Startup Error on Mac Release

### ISSUE THREAD

**Issue by rigelrozanski** [felixrieseberg/windows95#135]
Got this error (running mac Mojave 10.14.1) for the latest release. No window frame loads

`
Uncaught Exception: Error: Could not get code signature for running application at initUpdater (/private/var/folders/yp/_cy_ljl90v307wgrg6wp91140000gn/T/AppTranslocation/D198F7DB-438D-4F9D-98AC-7419CAA23A99/d/windows95.app/Contents/Resources/app/node_modules/update-electron-app/index.js:54:15) at App.<anonymous> (/private/var/folders/yp/_cy_ljl90v307wgrg6wp91140000gn/T/AppTranslocation/D198F7DB-438D-4F9D-98AC-7419CAA23A99/d/windows95.app/Contents/Resources/app/node_modules/update-electron-app/index.js:33:43) at App.emit (events.js:199:15)`

![Screen Shot 2019-05-20 at 4 09 33 AM](https://user-images.githubusercontent.com/20132176/58006051-1e727e80-7ab5-11e9-85e6-bf0b77df21a3.png)

**Comment by HSoeren** [comment]
I have a similar error:
`Uncaught Exception:
Error: Could not get code signature for running application
    at initUpdater (/Applications/windows95.app/Contents/Resources/app/node_modules/update-electron-app/index.js:54:15)
    at App.<anonymous> (/Applications/windows95.app/Contents/Resources/app/node_modules/update-electron-app/index.js:33:43)
    at App.emit (events.js:199:15)`

![Bildschirmfoto 2019-05-21 um 10 25 17](https://user-images.githubusercontent.com/25493517/58080094-cd48b480-7bb2-11e9-8250-307485625b52.png)

[Version 2.1.0](https://github.com/felixrieseberg/windows95/releases/tag/v2.1.0)

macOS Mojave - 10.14.4

**Comment by Araiguma90** [comment]
I ran into the same issue. 
Worked for me after codesigning it: 
codesign -f -s - --deep /Applications/windows95.app/

Hope it helps for you :)

**Comment by felixrieseberg** [comment]
Ugh, damn, that's bad.

**Comment by felixrieseberg** [comment]
Sorry everyone, this is now fixed. Thanks for the reports!
