### ISSUE TITLE
No Cmd!

### ISSUE THREAD

**Issue by BeroNaruto** [felixrieseberg/windows95#14]

**Comment by rygorous** [comment]
Windows 95 doesn't have CMD. That's NT! It's all about command.com, man.

**Comment by Lord-Nightmare** [comment]
I'm guessing this is something related to libv86.js lacking 16-bit protected mode emulation.

**Comment by felixrieseberg** [comment]
See #50. In short, hit Alt+Enter to exit fullscreen and fix the garbled mess!
