### ISSUE TITLE
Multiple anti-virus packages showing FileRepMalware detection

### ISSUE THREAD

**Issue by RepoMeister** [felixrieseberg/windows95#142]
The file windows95.exe was flagged by the following:
AVG reported it as FileRepMalware
Aegis reported it as Trojan.Win32.Generic.4!c
MacAfee reported it as Artemis 

In addition, it was stopped from silently accessing the url: diggingrationspace.com

**Comment by felixrieseberg** [comment]
Some AV software is incorrectly identifying the auto-updater (which is a security feature!) as malware. It's true, the updater is capable of downloading and executing updates, that's its purpose.

Thanks for bringing this to my attention, I appreciate the effort: But for now, I can only point at https://github.com/Squirrel/Squirrel.Windows/issues/218 and offer that all my source code is public.
