### ISSUE TITLE
Windows95 running on MacOS (10.13.6) freezes when trying to access Floppy A:

### ISSUE THREAD

**Issue by AdrianBrancato** [felixrieseberg/windows95#15]
I was trying a few things, went to My Computer, selected "Floppy Drive A:"   The Win95 app froze.  Mac OS was fine, but couldn't do anything inside the Win95 app.

Restarted the app, same screen.  Deleted all instances of the app on my Mac.  Opened the zip file again and ran the app, same screen.
Went into Activity Monitor dropped three processes related to the app, same screen.

![screen shot 2018-08-23 at 5 29 54 pm](https://user-images.githubusercontent.com/42658130/44554142-cd885200-a6fd-11e8-9035-40a1d0cac08c.png)

Restarted the Mac.  All was fine with the Mac but Win95 app had same screen.
Re-downloaded the original zip file.  Still, the exact same screen.

There's something persistent.

**Comment by felixrieseberg** [comment]
Hi the `Reset State` button and then run Windows 95.

**Comment by AdrianBrancato** [comment]
Felix,

I was about to start searching for the "Reset State button", but there it was.   Dummy.

Felix thanks very much for your entertaining app and for your prompt attention to my "problem".
Secretly, I'd love to have a Windows app that would allow me to run Quicken for Windows, and drop Parallels.
Your "Windows95.app" is a tantalizing step in that direction.

Adrian

On Aug 23, 2018, at 7:10 PM, Felix Rieseberg <notifications@github.com> wrote:

Hi the Reset State button and then run Windows 95.
