### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by ChrDur1** [felixrieseberg/windows95#166]
I'm on MacOS 10.11, and when i click run Windows 95, it goes black. can i fix this, or it takes long to load?

**Comment by ChrDur1** [comment]
This issue is half closed. it works on Windows 10, but how will it work on iMac?

**Comment by SirKnightTG** [comment]
It's not working for me on Windows 10. I get a black screen with a _ near the middle of the screen.

**Comment by ChrDur1** [comment]
i just needed the newest version
