### ISSUE TITLE
The Wifi is not Working ⚒ in Windows 95

### ISSUE THREAD

**Issue by kevinmahrous** [felixrieseberg/windows95#180]
In 2020 We use Wifi not Modem I searched for a software or Module to run the Internet .... After a lot of search i seen a method 
But This Method Not work in the Emulator
Link for the Method: https://www.sysnettechsolutions.com/en/connect-windows-95-internet-virtualbox/
I hope you resolve the issue

**Comment by parkerlreed** [comment]
This emulator does not support networking.

**Comment by kevinmahrous** [comment]
> 
> 
> This emulator does not support networking.

Thanks Parkerlreed
