### ISSUE TITLE
Starting MS-Dos Prompt on MacOS causes Windows 95 to freeze

### ISSUE THREAD

**Issue by phlogistic** [felixrieseberg/windows95#2]
I don't care if you fix it tho, this electron app is still awesome!

**Comment by jfmherokiller** [comment]
this might be an issue with v86

if you look at the readme of v86

```
An x86 compatible CPU. The instruction set is around Pentium 1 level. Some features are missing, more specifically:

    Task gates, far calls in protected mode
    16 bit protected mode features
    Single stepping
    MMX, SSE
    A bunch of FPU instructions
    Some exceptions
```

Specificly the line 16bit protected mode features. I think from my own experience that windows 95 makes use of msdos by task switching into 16bit protected mode which makes windows 95 pause until you close the window.  This can be seen on real hardware under the fact that you can only run a single msdos window. 

additional informaion can be seen here [http://www.fandecheng.com/personal/interests/ewindows/advanced_windows/win95_multitask.htm](http://www.fandecheng.com/personal/interests/ewindows/advanced_windows/win95_multitask.htm)

**Comment by nhblock** [comment]
I ran into the same issue just now by trying to execute command.com, in v1.0.

**Comment by Miserlou** [comment]
![screen shot 2018-08-23 at 2 30 07 pm](https://user-images.githubusercontent.com/139987/44544754-1978ce00-a6e1-11e8-953e-e8caa0852436.png)

Same issue here, was hoping to play Doom

**Comment by johnwcowan** [comment]
Instead of trying to use the native MS-DOS box, use https://www.dosbox.com inside the Win95 emulation.  That allows you to run multiple boxen and doesn't depend on the details of v86.  Note: I haven't tried this.

**Comment by alexpersian** [comment]
@Miserlou check issue #11 for some details on how to get DOOM running.

**Comment by felixrieseberg** [comment]
Quick fix: Hit Alt + Enter. I'll close this in favor of https://github.com/felixrieseberg/windows95/issues/50.
