### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [felixrieseberg/windows95#20]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by frzifus** [comment]
that would be great

**Comment by malept** [comment]
Given https://github.com/flathub/flathub/wiki/App-Requirements#license I doubt it would be wise to submit it. However, I have a branch that I need to turn into a PR so that a flatpak file can be produced when releasing, in addition to deb and rpm.
