### ISSUE TITLE
Unable to open Windows95.app on MacOS BigSur version 11.0.1

### ISSUE THREAD

**Issue by grantis** [felixrieseberg/windows95#205]
Unable to open the app. 

MacOS opens a popup "You can’t open the application “windows95.app” because this application is not supported on this Mac." 😢 

Any ideas on how this can be fixed?

**Comment by Tonytheconqeror** [comment]
I canning open it too on my 27 inch iMac 2019 running macOS Big Sur(macOS 11.1).I really love the app and want to use it,is there any solution?😥

**Comment by Tonytheconqeror** [comment]
I can use it now!😎The link for m1 chip and intel chip seem to be swap, that's probably why I can't use it.
