### ISSUE TITLE
Need a way to mount iso CD images

### ISSUE THREAD

**Issue by helje5** [felixrieseberg/windows95#21]
We need to be able to install software. Now!

**Comment by felixrieseberg** [comment]
v1.1, just released, let's you mount floppy disk images.

**Comment by helje5** [comment]
Yeah! Just seen it :-) But I need CD images, presumably this works as well, or just floppys?

**Comment by helje5** [comment]
I'm still waiting in the hope it is just "busy" processing the 200MB image, but it seems I can't mount a CD img that way. (white screen, macOS)

**Comment by Chrozayis** [comment]
yep, blank screen for me too when trying to mount a cd iso (Manjaro).
Also, if we have to reboot to mount drives multiple drive bays would be really really nice

**Comment by pale2hall** [comment]
Instead of trying to mount a CD, you could break the 200mb image into 139 individual 1.44mb floppy disks.

**Comment by CodePrinz** [comment]
Same for me, only trying to mount a file with a size of 38 MB.

**Comment by emanuelrv** [comment]
is very important

**Comment by eidolon232** [comment]
I have tried using Power Iso to create a floppy image with a simple .txt file in it. When I try to open the disk under Win 95, the file shows up, but is missing all the text in it. Extracting the image file in win10 shows that everything is there. I have tried using some floppy disk images with drivers for a CD drive, but  was unable to mount them at all.
Has anybody managed to transfer files, yet?

**Comment by helje5** [comment]
I'm not entirely sure what the new 1.2 feature:

> You can now mount the disk image (on Windows 10 and macOS)

means. I can see the "show disk image" button, which shows the Windows95.img.

Does it mean we could mount the image on say macOS, add stuff to it, then replace it to inject more software? :-)
I'm still very much longing to be able to try some software I have on CD :-)

**Comment by felixrieseberg** [comment]
> Does it mean we could mount the image on say macOS, add stuff to it, then replace it to inject more software? :-)

@helje5 That's exactly what it means! Double-click it (if on macOS) and start adding stuff to it. Windows might want to start ScanDisk because it's surprised by those files, but that's how it works!

**Comment by MJB-Founder** [comment]
@felixrieseberg  Hey felix, for the holidays (and during COVID) my entire extended family is interested in playing the old Softkey Shareware 2000 games on Windows 95. There's an internet archive of the game file (ISO format) available at the following link:  [https://archive.org/download/SoftkeyShareware2000games] This was a treasured, memorable game CD. 

When I try to mount the disk using the provided tool, I get a blank white screen when starting Windows 95 again. Happy to pay a sum for help here. Let me know your thoughts.

**Comment by facumastandrea** [comment]
Hi, what I did was to open the .img file, add what I needed and save it, then just restart. Problem is I can´t install what I want because it´s asking me to use autorun... any solution? THX!!!!!!!!!!!!!!

**Comment by jgeary** [comment]
> > Does it mean we could mount the image on say macOS, add stuff to it, then replace it to inject more software? :-)
> 
> @helje5 That's exactly what it means! Double-click it (if on macOS) and start adding stuff to it. Windows might want to start ScanDisk because it's surprised by those files, but that's how it works!

This doesn't work, though! When I go to the disk image and mount it, it mounts a read-only volume. I cannot add anything to it. What should I do?
