### ISSUE TITLE
Could someone upload the installer to a server other than GitHub? I can't manage to download it within the GitHub download authentication timeout.

### ISSUE THREAD

**Issue by hello-smile6** [felixrieseberg/windows95#225]
Please!

**Comment by arcade-smasher** [comment]
I could send you the link, 
are you windows 32 bit or windows 64 bit, 
do you want linux 64 bit DEP or linux 64 bit RPM, 
are you mac?

**Comment by hello-smile6** [comment]
I was actually on Windows.

**Comment by arcade-smasher** [comment]
If you still need it, 64-bit: [https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-x64.exe](https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-x64.exe), 32-bit: [https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-ia32.exe](https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-ia32.exe)

**Comment by hello-smile6** [comment]
> If you still need it, 64-bit: https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-x64.exe, 32-bit: https://github.com/felixrieseberg/windows95/releases/download/v2.3.0/windows95-2.3.0-setup-ia32.exe. I really hope this helps you!

Github was the problem... Also, I don't need the installer link anymore, although I'd love to try this again now! Thanks!
