### ISSUE TITLE
Add "Don't know what kind of chip you have?" For linux

### ISSUE THREAD

**Issue by iAmInActions** [felixrieseberg/windows95#234]
I saw that you have a section in mac and windows field that says:
"❓ Don't know what kind of chip you have? _[system-specific instructions]_"

Under linux, there is a command called `uname` that give you exactly that information.
So, if you want to have your download section contain that useful piece of information for linux, why not add something like this:

"❓ Don't know what kind of chip you have? Open a terminal and type `uname -p` for info."

**Comment by underjack** [comment]
uname -p will give the arch type, but not specific processor type.  And on the Linux system for windows install on my PC, it gives "unknown".

The contents of /proc/cpuinfo is much more reliable and descriptive.

**Comment by iAmInActions** [comment]
/proc/cpuinfo doesn't show any information about the architecture. It only shows the name of the chip. For knowing what to download, you need to know the architecture. The name and amount of cores is irrelevant for this. And if you use windows, you can just simply use the windows instructions.

**Comment by felixrieseberg** [comment]
I'm simply assuming that Linux users are savvy enough to _know_ what they're running - as opposed to many of my friends, who just walk into a store and say "one computer please" 😉
