### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by G-Rowell** [felixrieseberg/windows95#248]
Hi,

your repo here,

Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4

Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/Windows95

They also have a GitHub org, where they likely also have some stolen work: https://github.com/tesseract-org.

Checkout their all their personal repos...

I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.

Galen

**Comment by Derpez** [comment]
@G-Rowell 

The person that you have stated can do whatever they want with this code...

The License of this repo states that you can "distribute" this software and "copy" this software...

That is the whole point of a open source license.

Link to license:
https://github.com/felixrieseberg/windows95/blob/master/LICENSE.md

**Comment by felixrieseberg** [comment]
Ah, that's totally fine. Thanks for reporting!
