### ISSUE TITLE
Is it possible to put files from the host machine into the app?

### ISSUE THREAD

**Issue by Luigibrine2000** [felixrieseberg/windows95#25]
Is there a way to put files (png, jpg, txt, etc.) from the host computer into the app? If so, how?

**Comment by felixrieseberg** [comment]
It is! You can mount the disk image and put files into it. I might make that easier in a future release, but I'd also gladly take a PR!

**Comment by zelonght** [comment]
Can you explain a bit on how to mount it?

**Comment by chrsjhnsn** [comment]
You sure can, I just installed Microsoft Bob.

Clone the repo, download the images, put them in the right spot according to this project's readme, mount windows95.img and add your files. Build according to the readme. After starting the local instance, choose the option in the bottom right (pre-windows) that lets you discard the current state and boot from scratch. Then you'll be in your own instance with whatever files you added.

**Comment by chrsjhnsn** [comment]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/7016191/44603204-f9fca680-a7af-11e8-8ba2-f43235421c8e.png">
👌🤘😂

**Comment by zelonght** [comment]
Thank @chrsjhnsn 
But if we can make that windows 95 connected to Internet then we can do a lot of thing, download easier and no need advance step to mount, build things.

**Comment by chrsjhnsn** [comment]
@zelonght Oh, definitely. That would be much better. But it wasn’t @Luigibrine2000’s question, they just wanted to know if it could be done today.

And the build process takes <5 minutes, it’s not too bad.

**Comment by Gandalf-AwA** [comment]
@felixrieseberg  

Dear Felix,
Your Win 95 is amazing! :-) Yes, please make it more easy in future, to:

**1)** Increase / Change the storage of Win95 D: Drive
**2)** Make a Folder in Host Computer, and all files in this folder are availabe in Win95 App, e.g. as network device. :-)

Thank you for your great work & kind regards,
Bernd

**Comment by felixrieseberg** [comment]
I've now documented how add files to the image. [It's still not as convenient as I'd like it to be](https://github.com/felixrieseberg/windows95/blob/master/HELP.md#i-want-to-install-additional-apps-or-games), but it _kind_ of works.
