### ISSUE TITLE
i need to connet to the web in the app but i cant can someone help me get it work PS don't know how to code

### ISSUE THREAD

**Issue by jonareofromrunescape** [felixrieseberg/windows95#268]
plz

**Comment by ST1NGRAY95** [comment]
use a virtual machine instead

**Comment by jonareofromrunescape** [comment]
well um all the vm's of windows 95 dont work for me can you pre install one for me with all the stuff like a working web browser like opera 9..64 and some fun programs

**Comment by jonareofromrunescape** [comment]
so yeah......

**Comment by hello-smile6** [comment]
@jonareofromrunescape #226 
Get the .img and try booting it in [v86](https://copy.sh/v86)

**Comment by jonareofromrunescape** [comment]
thats not what im saying all of the .img .ico all the ones ive found on the web non work so plz can you just make one i barely know anything about vms only have a XP one so yeah
![mario-thinking](https://user-images.githubusercontent.com/103080644/165193118-48c1759d-4fac-4829-89a8-3731f5c5c59d.gif)

**Comment by hello-smile6** [comment]
> that's not what i'm saying all of the .img .ico all the ones i've found on the web do not work so plz can you just make one i barely know anything about VM's only have a XP one so yeah ![mario-thinking](https://user-images.githubusercontent.com/103080644/165193118-48c1759d-4fac-4829-89a8-3731f5c5c59d.gif) me trying to fix my issues in my VM be like

JUST GET THE DISK IMAGE AND USE QEMU! ALSO, A .ICO FILE IS **NOT** A DISK IMAGE!!!

**Comment by hello-smile6** [comment]
@jonareofromrunescape https://wormhole.app/e89NY#P1hJKNjWCW4LQLZXWdM-0g
You have 24 hours to download it, or it will be deleted.

**Comment by jonareofromrunescape** [comment]
okay

**Comment by jonareofromrunescape** [comment]
sorry i did not get the message

**Comment by jonareofromrunescape** [comment]
it does not work?
![mario-thinking](https://user-images.githubusercontent.com/103080644/165205634-b68a0b09-e91b-412a-a716-ad1d87ab7818.gif)
questions are coming up in my head

**Comment by jonareofromrunescape** [comment]
oh wait

**Comment by jonareofromrunescape** [comment]
you left before finishing the upload so the link does not work

**Comment by jonareofromrunescape** [comment]
(slaps head)

**Comment by jonareofromrunescape** [comment]
> > that's not what i'm saying all of the .img .ico all the ones i've found on the web do not work so plz can you just make one i barely know anything about VM's only have a XP one so yeah ![mario-thinking](https://user-images.githubusercontent.com/103080644/165193118-48c1759d-4fac-4829-89a8-3731f5c5c59d.gif) me trying to fix my issues in my VM be like
> 
> JUST GET THE DISK IMAGE AND USE QEMU! ALSO, A .ICO FILE IS **NOT** A DISK IMAGE!!!

also do not know how to code so qemu is not gonna work

**Comment by hello-smile6** [comment]
> > > that's not what i'm saying all of the .img .ico all the ones i've found on the web do not work so plz can you just make one i barely know anything about VM's only have a XP one so yeah ![mario-thinking](https://user-images.githubusercontent.com/103080644/165193118-48c1759d-4fac-4829-89a8-3731f5c5c59d.gif) me trying to fix my issues in my VM be like
> > 
> > 
> > JUST GET THE DISK IMAGE AND USE QEMU! ALSO, A .ICO FILE IS **NOT** A DISK IMAGE!!!
> 
> also do not know how to code so qemu is not gonna work

Then **ZioqKg== off.** You don't need to know how to to use qemu.
