### ISSUE TITLE
Containerize and develop a helm chart for k8s

### ISSUE THREAD

**Issue by toolboc** [felixrieseberg/windows95#27]
Containerize this thing and create the world's first Win95 cluster!

**Comment by justenb** [comment]
wen helm chart?

**Comment by toolboc** [comment]
@justenb ,

Containerization is complete and ready to merge in #52 
The idea of clustering Win95 in k8s is certainly enticing, but as-is, this repo requires a display to properly execute.  We need to figure that part out and then the dream of a Windows 95 cluster can become reality.
