### ISSUE TITLE
macOS: No work gets saved and OS always boots into Default State

### ISSUE THREAD

**Issue by suobset** [felixrieseberg/windows95#275]
Just created a website in Microsoft FrontPage for funsies. However, when I save my work and mount the disk image on my main computer, it does not show up. Moreover, Win 95 always boots into default state, not the state with my saved stuff. Does not matter if I turn it off using the menu options or by shutting it down. Any help would be appreciated (tbh might fork and try to create a pull request as well). 

Thanks for all the help, and for such an amazing product!!! :D 

PS: Running on macOS Monterey on a 2017 MacBook Pro.

**Comment by felixrieseberg** [comment]
Thanks for the report! This his hopefully now fixed 🙇
