### ISSUE TITLE
Missing viruses

### ISSUE THREAD

**Issue by Eiyeron** [felixrieseberg/windows95#29]
Hello.

I'm genuinely amazed (but not that much surprised) one could actually emulate a x86 CPU close enough to run that good ol' Windows 95. That's quite the achivement to see that after years of taking jabs at browsers becoming close to VMs, they ended up as such.

I guess the next step is adding viruses? I mean, I'm a fan of Danooct1 and his videos about the world of old-timer viruses, and to see them evolving in their natural virtualized state a bit like this [xkcd](https://xkcd.com/350/) could be a fun way to showcase them online, I guess?

Amazing work, nonetheless. Have a nice day and ood luck with your future projects!

**Comment by felixrieseberg** [comment]
You can now open the disk image and add whatever you like!
