### ISSUE TITLE
Native Mouse Pointer vs. Windows95 Mouse Pointer

### ISSUE THREAD

**Issue by frogg** [felixrieseberg/windows95#3]
somehow I managed to have two mouse pointers (the native macOS one and the virtual windows95 one):

![img_5823](https://user-images.githubusercontent.com/5204169/44536477-de849380-a6fc-11e8-84a1-31fb309718e7.jpg)

the relative movements of the simulated mouse pointer was still correct though. 

Running macOS Mojave 10.14 Beta (18A371a).

**Comment by alexcourouble** [comment]
This happens when you press esc to be able to move the macos pointer outside of the window. 

If you hit esc again, you'll only see the windows95 pointer.

**Comment by frogg** [comment]
Ah Perfect, thanks!
