### ISSUE TITLE
Is it possible to run Office 2003

### ISSUE THREAD

**Issue by ezdora** [felixrieseberg/windows95#30]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

**Comment by BaRRaKudaRain** [comment]
Office 2003 can't run on Windows 9x kernel.
