### ISSUE TITLE
Please please install Deluxe Paint II & Ami Pro

### ISSUE THREAD

**Issue by rpelaez** [felixrieseberg/windows95#35]
Please please install Deluxe Paint II & Ami Pro

**Comment by graspee** [comment]
That would be copyright infringement. Oh wait it's already copyright infringement.

**Comment by jvyden420** [comment]
Download it and do it yourself.

**Comment by rpelaez** [comment]
It's "abandonware"
Here the download link: https://www.maquinitas.org/pc-abandonware/aplicaciones-pc-y-emuladores-dos/deluxe-paint-2/

**Comment by felixrieseberg** [comment]
Hey, thank you for taking the time to fill out an issue! We're currently reserving GitHub issues for bugs and features someone is working on, so I'm closing this in the meantime.

Please feel free to reopen if I misunderstood you 🙇
