### ISSUE TITLE
Ability to Install Netscape Navigator

### ISSUE THREAD

**Issue by brittonbeckham** [felixrieseberg/windows95#41]
Would be awesome to run good 'ole Netscape. Can I get some up-vote love?

Have the installer  on the desktop as a temptation for those interested in running it.

**Comment by vogtmh** [comment]
You don't have any network connection yet, so it doesn't make sense to install Netscape atm ;-)

**Comment by felixrieseberg** [comment]
Still no network, but I _did_ install Netscape 2.0.
