### ISSUE TITLE
Scaling/HiDPI support

### ISSUE THREAD

**Issue by vanyasem** [felixrieseberg/windows95#43]
I am using a 4k monitor with x2 scaling. The canvas with Windows doesn't seem to scale or align properly, it just gets centered. 
![2018-08-24-210024_1927x1289_scrot](https://user-images.githubusercontent.com/13350458/44600265-6f349f80-a7e1-11e8-8982-57ffa848706f.png)

If I manually override the scaling with `--high-dpi-support=1 --force-device-scale-factor=1`, it works as expected:
![2018-08-24-210453_1290x874_scrot](https://user-images.githubusercontent.com/13350458/44600282-7c518e80-a7e1-11e8-8937-511992282a3c.png)

**Comment by benwiley4000** [comment]
I believed this is already fixed in master: https://github.com/felixrieseberg/windows95/pull/17

**Comment by vanyasem** [comment]
oops, I did a quick search by "scaling" and "hidpi", which resulted in no results. Sorry for a duplicate.
