### ISSUE TITLE
The performance is too good

### ISSUE THREAD

**Issue by Dzordzu** [felixrieseberg/windows95#44]
I suggest adding a new feature that will actually slow that thing down, in order to simulate a real-life windows system

**Comment by djsipe** [comment]
HAhahaha.

**Comment by jvyden420** [comment]
I think PCem does this too, would be neat.

**Comment by adrianandronache** [comment]
No-no, don't! I am just downloading the thing now, and I really want something FAST. I am sick and tired about the real Windows and how this is pulling ultrafast systems to a crawl; let us enjoy the good old days fastness. Hope Win95 will be able to access the new, spacious harddrives... but I know that maybe this is too much to ask. I will see.

**Comment by adrianandronache** [comment]
Ha!; it is aready slooow. Probably because of the virtual machine, combined with my actual system which is a netbook. The mouse pointer is lagging; and the video driver is drawing windows frames and background images very slow.

**Comment by awkspace** [comment]
@adrianandronache If it's speed you want, this is one of the slowest ways to virtualize Win95. A native virtualization program would be much better, like VirtualBox or VMWare.

**Comment by adrianandronache** [comment]
okay; i was initially thinking the OS will be useful for doing something, but is just for fun (and nostalgia).

**Comment by felixrieseberg** [comment]
🥇
