### ISSUE TITLE
Publish Windows 95 to Windows Store with "electron-windows-store" ^TM

### ISSUE THREAD

**Issue by toolboc** [felixrieseberg/windows95#45]
Use [electron-windows-store](https://github.com/felixrieseberg/electron-windows-store) to turn the Windows 95 electron app into a Windows Appx Package and publish it to the Windows Store!

**Comment by jvyden420** [comment]
Cant you publish normal apps to the microsoft store now?

**Comment by toolboc** [comment]
An appx might allow for operability on other Win10 devices, like Xbox One and Hololens.  That could be fun.

**Comment by felixrieseberg** [comment]
I _feel_ like they won't let me do that, so I'd rather not try 🤣
