### ISSUE TITLE
Windows XP Support

### ISSUE THREAD

**Issue by Stephen-Leibowitz** [felixrieseberg/windows95#51]
I appears that the only version to run on Windows is
windows95-1.1.0-setup-x64.exe

Perhaps you could make available an X86 version to run on Windows XP?

Thank you.

**Comment by nlogozzo** [comment]
Support for Windows XP ended in 2014 and 4 years later I don't believe developers are really supporting Windows XP. And even if an x86 version was released, I think Windows 7 would be the minimum supported Windows OS

**Comment by felixrieseberg** [comment]
Hey! I'll make an x86 version, but I'm afraid that it still won't run on Windows XP - Windows 7 is the oldest version of Windows this toy will run on. Sorry!
