### ISSUE TITLE
Hi Could this be used by Linux users for updating hardware Bios?

### ISSUE THREAD

**Issue by phd21** [felixrieseberg/windows95#54]
Hi Felix,

First, thanks for doing this for everyone to try and use...

Could this be used by Linux users for updating hardware Bios?

Best regards,
Phil (phd21)

**Comment by joel0** [comment]
Nope.  It's an emulator, so the guest OS doesn't have direct access to hardware.  You can think of it like how you can't update your hardware BIOS from within VirtualBox.
