### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by cunidev** [felixrieseberg/windows95#56]
Because why not? It's Electron :P

**Comment by luckcolors** [comment]
I was about to ask too. :grin:

**Comment by benwiley4000** [comment]
Electron's for desktop apps.

**Comment by luckcolors** [comment]
Right but we could use something like cordova for building an apk.

**Comment by luckcolors** [comment]
I can probably look into it.

**Comment by luckcolors** [comment]
I think it is going to be expected that you'll need to plug in a keyboard and mouse to use, though if anyone knows how to add UI overlays for that feel free to add that :) .

**Comment by luckcolors** [comment]
I think it is going to be expected that you'll need to plug in a keyboard and mouse to use, though if anyone knows how to add UI overlays for that feel free to add that. :)

**Comment by elvokibet** [comment]
Stacked

**Comment by felixrieseberg** [comment]
I certainly won't do that (I also don't have an Android device), but I'm sure you _could_ make that work.

I probably wouldn't go the JavaScript route though 😅
