### ISSUE TITLE
Isn't this piracy?

### ISSUE THREAD

**Issue by kingofdunthorpe** [felixrieseberg/windows95#57]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

**Comment by felixrieseberg** [comment]
My short answer: If and when MS asks me to take it down, I would.

Practically speaking, I’ve worked for the company for many years, have a deep love for it, and manya, many people at Microsoft have seen (and even contributed to) this app. There’s numerous websites offering Windows 95 as a download. This is basically an area where the company has so far been kind enough to just kindly look the other way.
