### ISSUE TITLE
Installed windows95-macos-1.2.0.zip - How to fully uninstall all files and components?

### ISSUE THREAD

**Issue by DinkumThinkum** [felixrieseberg/windows95#58]
Amazing app.  Congrats and thanks.  I enjoyed giving it a test drive.  

How do I completely uninstall the app?  Here's what I noticed.  

After installing the MacOS 1.2 version, I went through playing Free Cell, adjusting the screen resolution and exploring the menus.  Then I found that I had bricked the app, the Win95 mouse was unresponsive and the app would not run.

I thought that I could simply delete the app and rerun the download and run process to get going again.  When this did not work, I searched through ~/Library/Caches/* and. ~/Library/Preferences/* and ~/Library/Saved Application State/com.felixrieseberg.windows95.savedState for hints of components to delete in order to completely uninstall the app.  I found a few files named like "com.felixrieseberg.windows95", "com.felixrieseberg.windows95.ShipIt" and "com.felixrieseberg.windows95.savedState" and etc. and I deleted those.  

To be certain that there were no leftover components, I reinstalled and ran the app to see if any of my Windows95 settings persisted .. and they did.  Apparently the Win 95 state persists and the mouse is not responsive.   I could get to the "Start Windows 95" screen and still no go.

So how do I completely uninstall the app, manually or otherwise?  A little help please?

Thanks

**Comment by vogtmh** [comment]
You could use an app like this one: https://itunes.apple.com/de/app/app-cleaner-uninstaller/id1013897218?mt=12

**Comment by DFELD2005** [comment]
I found several references to windows95 installation using an older version of AppCleaner.
Here is a screen-shot of the listing
![windows95-appcleaner](https://user-images.githubusercontent.com/42745472/44670241-1edf5c80-a9f0-11e8-9d3f-c7bbb0bcaf8f.png)

**Comment by felixrieseberg** [comment]
👆 That looks right to me!
