### ISSUE TITLE
how do i find ./src/images/windows95.img file

### ISSUE THREAD

**Issue by mrh-jishan** [felixrieseberg/windows95#61]
I am trying to run the project from repository but i am not able to boot it since I could not find the .img file. Can anybody help me to find the file?

here is the log:

![screenshot from 2018-08-26 20-45-54](https://user-images.githubusercontent.com/16862701/44628382-1431b280-a971-11e8-87aa-5aa8999efe6d.png)

**Comment by pdxjohnny** [comment]
https://github.com/felixrieseberg/windows95/blob/1ae2e5d546105912f9e95cd8f5bb1d7eeade1b00/README.md#contributing

**Comment by iSn0we** [comment]
open the App and click on "Show disk image"

**Comment by felixrieseberg** [comment]
Thanks all, seems like the question was answered!
