### ISSUE TITLE
Running a *.bat file breaks the screen

### ISSUE THREAD

**Issue by MatthyPlayz** [felixrieseberg/windows95#62]
Soooo I ran a test file in a *.bat format and I think it permanently broke the machine display.
![oh](https://user-images.githubusercontent.com/34276633/44629506-6695b380-a91e-11e8-8c03-a2a303a3d818.png)

**Comment by ZanderBrown** [comment]
Duplicate of #50?

**Comment by felixrieseberg** [comment]
Solved! See: https://github.com/felixrieseberg/windows95/issues/50
