### ISSUE TITLE
Vmware unity.

### ISSUE THREAD

**Issue by Nukley** [felixrieseberg/windows95#67]
Try to make a feature similar to vmware unity, to have windows 95 applications run seamlessly on the modern desktop. Also, try adding the ability to upgrade to windows 98 SE please.

**Comment by awkspace** [comment]
I think you might be overestimating the scope of this project...

**Comment by incizzle** [comment]
Yes this does seem like a lot to ask of such a project.

**Comment by felixrieseberg** [comment]
Sorry, you might be looking for an actual VM software 😅
