### ISSUE TITLE
Missing 3D Pinball Space Cadet :)

### ISSUE THREAD

**Issue by olsonjosh** [felixrieseberg/windows95#7]

**Comment by drewbrew** [comment]
Wasn't that part of Microsoft Plus?

**Comment by kadamwhite** [comment]
![image](https://user-images.githubusercontent.com/442115/44541814-1bd72a00-a6d9-11e8-90b5-6b5c3eadc4e4.png)
Good thing I saw this bug before that download finished, had time to abort :)

More seriously, yes, with Windows 95 it was part of Plus!... it only got bundled in subsequent versions (up until XP).

**Comment by valassis-nick** [comment]
@drewbrew yes, you are correct: https://en.wikipedia.org/wiki/Microsoft_Plus!

**Comment by drewbrew** [comment]
LOL, GitHub didn't recognize the ! as part of the URL.

**Comment by valassis-nick** [comment]
LOL. C'mon GitHub!

**Comment by Miserlou** [comment]
Also missing: https://en.wikipedia.org/wiki/SkiFree

**Comment by Crysikrend** [comment]
Get this in and I'll download. I'll wait.

**Comment by felixrieseberg** [comment]
Sorry, that won't be in there. But! You could download it, add it to the disk image, and have some fun with it.

**Comment by 1j01** [comment]
[Windows 2000 on jslinux](https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/win2k.cfg&mem=192&graphic=1&w=1024&h=768) has 3D Pinball *(Programs > Accessories > Games > 3D Pinball)*, but 1. there's no sound, and 2. I had some trouble getting the controls to work, had to unstick some modifier key(s) for some reason? maybe that's just on my end tho
