### ISSUE TITLE
Windows 98

### ISSUE THREAD

**Issue by AndrejaN** [felixrieseberg/windows95#75]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

Hi, sorry this is not an issue, but i would like to ask you is it possible to make Windows SE 98 run under Mac and Linux, just like this Windows 95 distribution?

Thanks in advance

**Comment by felixrieseberg** [comment]
It is - if you sub in a hard drive image with Windows 98, you're probably off to the races! See https://github.com/copy/v86 for more details.
