### ISSUE TITLE
Random things I found and a suggestion

### ISSUE THREAD

**Issue by Xbox180** [felixrieseberg/windows95#78]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

So I've been playing around with it for a few days, and I found some things. I don't know if my hardware would effect anything, so I'm going to list it.
Ryzen 7 2700U
Vega 10
8 Gigs or Ram
285 Gig SSD
Win 10 Version 1803

So, on of the first things I noticed was that when you try to shut down or restart Windows 95 from with in Windows, it doesn't work. I get a small white line in about the middle of the screen
![screenshot 4](https://user-images.githubusercontent.com/17104044/44800197-d35db780-ab83-11e8-814c-00d717f50502.png)

I know that other people have reported this, but one said that it was on macOS, and another didn't post what OS.

The second thing is that when I try to mount the .img Windows says that the img is corrupted. Even if I do the Installer exe or the standalone zip.

Third things is a suggestion. I would like to connect the program to the internet just as a 'just-cause-I-can' sort of thing, but I'm not sure if that would pose a security risk to the physical computer. If it does, ignore this.

P.S. I would like a Pull just to play with Java, like you said.

**Comment by SecKarma** [comment]
I don't think there'll be any security risk because at the end the image is running on an emulator using seabios.
when we start to use docker and volumes for instance, yeah that might be sort of a risk, in case you're on a windows machine (with no AV or Firewall)

**Comment by felixrieseberg** [comment]
Hey, thank you for taking the time to fill out an issue! We're currently reserving GitHub issues for bugs and features someone is working on, so I'm closing this in the meantime.

Please feel free to reopen if I misunderstood you 🙇
