### ISSUE TITLE
v1.3 doesn't show anything for me on macOS 10.13.6

### ISSUE THREAD

**Issue by helje5** [felixrieseberg/windows95#83]
I get the boot screen, but when I click the "Start Windows 95" button the screen goes black.

Log says:
```
Uncaught TypeError: Cannot read property 'timer' of null
    at CPU.run_hardware_timers (libv86.js:624)
    at CPU.do_run (libv86.js:620)
    at CPU.main_run (libv86.js:603)
    at v86.do_tick (libv86.js:115)
    at libv86.js:116
```

**Comment by helje5** [comment]
Hm, same w/ 1.2

**Comment by zeckesiob** [comment]
Hi! Open Finder and go to Library > Application Support (Menu "Go" then press Alt). You will find the Folder "windows95", rename or delete it and try again.

**Comment by helje5** [comment]
I can confirm that this fixes the issue, still shouldn't happen, right?

**Comment by zeckesiob** [comment]
Right, this shouldn‘t happen. The question is, what have you done within windows95 just bevore it happens first time..?

**Comment by helje5** [comment]
i didn’t do any tweaking before at all, so it was just starting the apps, having a look, quitting them.
i tried to mount a large img file as a floppy, but presumably that shouldn’t be related.

**Comment by felixrieseberg** [comment]
Hey, thank you for taking the time to fill out an issue! I believe that the issue was already fixed, so I'm closing this issue for now. Please feel free to reopen if I misunderstood you 🙇
