### ISSUE TITLE
Show Disk Image - Disc image file is corrupted

### ISSUE THREAD

**Issue by Duzeper** [felixrieseberg/windows95#91]
Cannot 'mount' virtual hard drive in Windows 10.
Double clicking the disk image gives the error 'Couldn't mount file - The disc image is corrupted'
I want to install old games that are incompatible with Windows 10.
I have tried both 64bit and 32bit installation. Same error with both

**Comment by ZacksH** [comment]
Use WinZip or 7-Zip to open the image. Do not try with Win10 mount tol

**Comment by anagnos3** [comment]
How are we supposed to add files to the image?

**Comment by HL3isComing** [comment]
Hi Duzeper,

I fixed this issue by loading the file with new mounting software. The program is not meant to be loaded with a zip application.

I was trying to load it with Daemon Tools, but that didn't work so I tried PowerISO. PowerISO worked for me. Once installed, all you have to do is load it up and copy and paste your files in. You'll notice when you load it that all of the files in there are what is included in the Windows 95 application.

Good luck!

**Comment by nathanielbatesprosser** [comment]
Lies to lies truth to truth . makes no since . now you know how I feel

**Comment by felixrieseberg** [comment]
Ah, common issue with Windows 10. I've documented how to [open the disk image here](https://github.com/felixrieseberg/windows95/blob/master/HELP.md#i-want-to-install-additional-apps-or-games), so I'm closing this for now.
