### ISSUE TITLE
Any plans for Internet support?

### ISSUE THREAD

**Issue by LOL-XDD** [felixrieseberg/windows95#94]
The main reason I'd want to use Windows 95 is to connect it to my current computer. I'd also like to see what new websites look like on the system. Any plans to support this?

**Comment by felixrieseberg** [comment]
I probably won't find the bandwidth to actually work on that. I'd gladly take a PR, but I have to tell you right now - given how big and complex modern websites are, there's not a single browser available for Windows 95 that'd be capable of even opening the majority of websites today, let alone successfully displaying it.

**Comment by parkerlreed** [comment]
I would assume the goal is to maybe load older sites more appropriate for the era :) 

Also there's a fairly recent Opera build for 98SE. Doesn't help much here though.

**Comment by Heath123** [comment]
> I probably won't find the bandwidth to actually work on that. I'd gladly take a PR, but I have to tell you right now - given how big and complex modern websites are, there's not a single browser available for Windows 95 that'd be capable of even opening the majority of websites today, let alone successfully displaying it.

This would be useful because I want to test my site on old things.
