### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Anthonyg5005** [felixrieseberg/windows95#95]
Can you please make one for windows xp 32-bit because I am trying to use it on a windows xp pc but it says it is not a valid win32 app.

Thank you

I just noticed my issue number is 95

**Comment by nlogozzo** [comment]
In Issue #51 , the creator said: "Hey! I'll make an x86 version, but I'm afraid that it still won't run on Windows XP - Windows 7 is the oldest version of Windows this toy will run on. Sorry!"

**Comment by jacobq** [comment]
Yes, I think that OS support is limited by [what ElectronJS supports](https://electronjs.org/docs/tutorial/support#supported-platforms), sorry.
